[2024-12-03T07:51:06.682+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T07:51:06.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_tripdata.transform_data_task manual__2024-12-03T07:50:56.545430+00:00 [queued]>
[2024-12-03T07:51:06.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_tripdata.transform_data_task manual__2024-12-03T07:50:56.545430+00:00 [queued]>
[2024-12-03T07:51:06.710+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-03T07:51:06.723+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-12-03 07:50:56.545430+00:00
[2024-12-03T07:51:06.732+0000] {standard_task_runner.py:64} INFO - Started process 3489 to run task
[2024-12-03T07:51:06.735+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_tripdata', 'transform_data_task', 'manual__2024-12-03T07:50:56.545430+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/dag_green_tripdata.py', '--cfg-path', '/tmp/tmpo5j055ow']
[2024-12-03T07:51:06.737+0000] {standard_task_runner.py:91} INFO - Job 205: Subtask transform_data_task
[2024-12-03T07:51:06.780+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_tripdata.transform_data_task manual__2024-12-03T07:50:56.545430+00:00 [running]> on host 39c047f38cb8
[2024-12-03T07:51:06.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_tripdata' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T07:50:56.545430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T07:50:56.545430+00:00'
[2024-12-03T07:51:06.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T07:51:07.033+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T07:51:07.034+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_green_tripdata.py", line 87, in transform
    df = df.astype({
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6513, in astype
    res_col = col.astype(dtype=cdt, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2024-12-03T07:51:07.047+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_tripdata, task_id=transform_data_task, run_id=manual__2024-12-03T07:50:56.545430+00:00, execution_date=20241203T075056, start_date=20241203T075106, end_date=20241203T075107
[2024-12-03T07:51:07.058+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 205 for task transform_data_task (int() argument must be a string, a bytes-like object or a number, not 'NoneType'; 3489)
[2024-12-03T07:51:07.117+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-12-03T07:51:07.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T07:51:07.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
