[2024-11-13T08:54:23.122+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T08:54:23.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:54:04.424075+00:00 [queued]>
[2024-11-13T08:54:23.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:54:04.424075+00:00 [queued]>
[2024-11-13T08:54:23.173+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-13T08:54:23.200+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-11-13 08:54:04.424075+00:00
[2024-11-13T08:54:23.211+0000] {standard_task_runner.py:64} INFO - Started process 2690 to run task
[2024-11-13T08:54:23.216+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'transform_data_task', 'manual__2024-11-13T08:54:04.424075+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpbyiqz11n']
[2024-11-13T08:54:23.220+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask transform_data_task
[2024-11-13T08:54:23.308+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:54:04.424075+00:00 [running]> on host 7a2cfb7b2df5
[2024-11-13T08:54:23.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T08:54:04.424075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T08:54:04.424075+00:00'
[2024-11-13T08:54:23.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T08:54:23.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T08:54:23.776+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 59, in transform
    df = df.to_frame()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_frame'
[2024-11-13T08:54:23.805+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=transform_data_task, run_id=manual__2024-11-13T08:54:04.424075+00:00, execution_date=20241113T085404, start_date=20241113T085423, end_date=20241113T085423
[2024-11-13T08:54:23.837+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 128 for task transform_data_task ('DataFrame' object has no attribute 'to_frame'; 2690)
[2024-11-13T08:54:23.887+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-13T08:54:23.935+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T08:54:23.942+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
