[2024-11-22T06:49:13.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T06:49:13.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_zone_map scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T06:49:13.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_zone_map scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T06:49:13.386+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-22T06:49:13.397+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_zone_map> on 2024-11-21 00:00:00+00:00
[2024-11-22T06:49:13.406+0000] {standard_task_runner.py:64} INFO - Started process 893 to run task
[2024-11-22T06:49:13.409+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'upload_zone_map', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmppajkf44v']
[2024-11-22T06:49:13.411+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask upload_zone_map
[2024-11-22T06:49:13.455+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.upload_zone_map scheduled__2024-11-21T00:00:00+00:00 [running]> on host 551e158b7a8c
[2024-11-22T06:49:13.522+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='upload_zone_map' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T06:49:13.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T06:49:13.525+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-11-22T06:49:13.526+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-22T06:49:13.527+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-22T06:49:13.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T06:49:13.528+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 114, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 362, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 334, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 257, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 315, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/oauth2/service_account.py", line 259, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/keys/service_account.json'
[2024-11-22T06:49:13.536+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nyc_green_taxi, task_id=upload_zone_map, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T064913, end_date=20241122T064913
[2024-11-22T06:49:13.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task upload_zone_map ([Errno 2] No such file or directory: '/opt/airflow/keys/service_account.json'; 893)
[2024-11-22T06:49:13.585+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-22T06:49:13.609+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T06:49:13.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
