[2024-11-12T08:54:19.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T08:54:19.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-12T08:50:34.006045+00:00 [queued]>
[2024-11-12T08:54:19.093+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-12T08:50:34.006045+00:00 [queued]>
[2024-11-12T08:54:19.094+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-11-12T08:54:19.128+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-11-12 08:50:34.006045+00:00
[2024-11-12T08:54:19.139+0000] {standard_task_runner.py:64} INFO - Started process 168 to run task
[2024-11-12T08:54:19.144+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'transform_data_task', 'manual__2024-11-12T08:50:34.006045+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmphd_91cqo']
[2024-11-12T08:54:19.148+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask transform_data_task
[2024-11-12T08:54:19.237+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-12T08:50:34.006045+00:00 [running]> on host 23d8db8c711b
[2024-11-12T08:54:19.403+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T08:50:34.006045+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T08:50:34.006045+00:00'
[2024-11-12T08:54:19.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T08:54:19.452+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T08:54:19.454+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 50, in transform
    df = pd.read_parquet(os.path.join(path_to_raw_dataset, filename_raw))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dataset/raw/nyc_taxi/green_tripdata_2023-01.parquet'
[2024-11-12T08:54:19.480+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=transform_data_task, run_id=manual__2024-11-12T08:50:34.006045+00:00, execution_date=20241112T085034, start_date=20241112T085419, end_date=20241112T085419
[2024-11-12T08:54:19.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task transform_data_task ([Errno 2] No such file or directory: '/opt/airflow/dataset/raw/nyc_taxi/green_tripdata_2023-01.parquet'; 168)
[2024-11-12T08:54:19.538+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-12T08:54:19.585+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T08:54:19.589+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
