[2024-11-22T06:49:24.821+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T06:49:24.836+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_green_tripdata_raw manual__2024-11-22T06:44:16.583277+00:00 [queued]>
[2024-11-22T06:49:24.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_green_tripdata_raw manual__2024-11-22T06:44:16.583277+00:00 [queued]>
[2024-11-22T06:49:24.844+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-22T06:49:24.855+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_green_tripdata_raw> on 2024-11-22 06:44:16.583277+00:00
[2024-11-22T06:49:24.863+0000] {standard_task_runner.py:64} INFO - Started process 923 to run task
[2024-11-22T06:49:24.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'upload_green_tripdata_raw', 'manual__2024-11-22T06:44:16.583277+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpv_69t8yp']
[2024-11-22T06:49:24.869+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask upload_green_tripdata_raw
[2024-11-22T06:49:24.910+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.upload_green_tripdata_raw manual__2024-11-22T06:44:16.583277+00:00 [running]> on host 551e158b7a8c
[2024-11-22T06:49:24.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='upload_green_tripdata_raw' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T06:44:16.583277+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T06:44:16.583277+00:00'
[2024-11-22T06:49:24.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T06:49:24.982+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-11-22T06:49:24.983+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-22T06:49:24.984+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-22T06:49:24.985+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T06:49:24.985+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 114, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 362, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 334, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 257, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 315, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/oauth2/service_account.py", line 259, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/keys/service_account.json'
[2024-11-22T06:49:24.994+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nyc_green_taxi, task_id=upload_green_tripdata_raw, run_id=manual__2024-11-22T06:44:16.583277+00:00, execution_date=20241122T064416, start_date=20241122T064924, end_date=20241122T064924
[2024-11-22T06:49:25.003+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task upload_green_tripdata_raw ([Errno 2] No such file or directory: '/opt/airflow/keys/service_account.json'; 923)
[2024-11-22T06:49:25.040+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-22T06:49:25.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
