[2024-11-22T09:27:42.807+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T09:27:42.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-22T09:27:25.611765+00:00 [queued]>
[2024-11-22T09:27:42.862+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-22T09:27:25.611765+00:00 [queued]>
[2024-11-22T09:27:42.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T09:27:42.901+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-11-22 09:27:25.611765+00:00
[2024-11-22T09:27:42.915+0000] {standard_task_runner.py:64} INFO - Started process 5967 to run task
[2024-11-22T09:27:42.922+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'transform_data_task', 'manual__2024-11-22T09:27:25.611765+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpsom1h9vg']
[2024-11-22T09:27:42.927+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask transform_data_task
[2024-11-22T09:27:43.026+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-22T09:27:25.611765+00:00 [running]> on host d0677a8ff53e
[2024-11-22T09:27:43.204+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T09:27:25.611765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T09:27:25.611765+00:00'
[2024-11-22T09:27:43.208+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T09:27:43.450+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T09:27:43.451+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 85, in transform
    df = df.astype({
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6513, in astype
    res_col = col.astype(dtype=cdt, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 101, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 146, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'trip_type'
[2024-11-22T09:27:43.482+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=transform_data_task, run_id=manual__2024-11-22T09:27:25.611765+00:00, execution_date=20241122T092725, start_date=20241122T092742, end_date=20241122T092743
[2024-11-22T09:27:43.506+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task transform_data_task (Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'trip_type'; 5967)
[2024-11-22T09:27:43.585+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-22T09:27:43.641+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T09:27:43.645+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
