[2024-11-13T06:39:42.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T06:39:42.955+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.load_tripdata_to_bq manual__2024-11-13T06:34:06.471657+00:00 [queued]>
[2024-11-13T06:39:42.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.load_tripdata_to_bq manual__2024-11-13T06:34:06.471657+00:00 [queued]>
[2024-11-13T06:39:42.972+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-13T06:39:43.000+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToBigQueryOperator): load_tripdata_to_bq> on 2024-11-13 06:34:06.471657+00:00
[2024-11-13T06:39:43.011+0000] {standard_task_runner.py:64} INFO - Started process 1166 to run task
[2024-11-13T06:39:43.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'load_tripdata_to_bq', 'manual__2024-11-13T06:34:06.471657+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpea67k33n']
[2024-11-13T06:39:43.019+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask load_tripdata_to_bq
[2024-11-13T06:39:43.097+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.load_tripdata_to_bq manual__2024-11-13T06:34:06.471657+00:00 [running]> on host 7a2cfb7b2df5
[2024-11-13T06:39:43.263+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='load_tripdata_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T06:34:06.471657+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T06:34:06.471657+00:00'
[2024-11-13T06:39:43.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T06:39:43.287+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-11-13T06:39:43.289+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-13T06:39:43.291+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-13T06:39:43.293+0000] {gcs_to_bigquery.py:381} INFO - Using existing BigQuery table for storing data...
[2024-11-13T06:39:43.382+0000] {gcs_to_bigquery.py:385} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'northern-shield-437204-m0', 'datasetId': 'nyc_taxi', 'tableId': 'green_tripdata'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://green_taxi_bucket/transform/tf_green_tripdata_2023-01.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False}}
[2024-11-13T06:39:43.385+0000] {bigquery.py:1702} INFO - Inserting job ***_nyc_green_taxi_load_tripdata_to_bq_2024_11_13T06_34_06_471657_00_00_e93fcc597c1c5690ccafd937b7efcd13
[2024-11-13T06:39:44.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T06:39:44.735+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 446, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table northern-shield-437204-m0:nyc_taxi.green_tripdata. Cannot add fields (field: vendor_id); reason: invalid, message: Provided Schema does not match Table northern-shield-437204-m0:nyc_taxi.green_tripdata. Cannot add fields (field: vendor_id)
[2024-11-13T06:39:44.752+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nyc_green_taxi, task_id=load_tripdata_to_bq, run_id=manual__2024-11-13T06:34:06.471657+00:00, execution_date=20241113T063406, start_date=20241113T063942, end_date=20241113T063944
[2024-11-13T06:39:44.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 107 for task load_tripdata_to_bq (400 Provided Schema does not match Table northern-shield-437204-m0:nyc_taxi.green_tripdata. Cannot add fields (field: vendor_id); reason: invalid, message: Provided Schema does not match Table northern-shield-437204-m0:nyc_taxi.green_tripdata. Cannot add fields (field: vendor_id); 1166)
[2024-11-13T06:39:44.823+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-13T06:39:44.857+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T06:39:44.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
