[2024-11-19T16:42:56.038+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:42:56.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:42:56.049+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:42:56.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:42:56.091+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:42:56.081+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:42:56.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:42:56.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.137 seconds
[2024-11-19T16:43:26.448+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:26.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:43:26.456+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:43:26.455+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:26.506+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:43:26.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:43:26.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:26.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.135 seconds
[2024-11-19T16:43:57.017+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:57.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:43:57.025+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:43:57.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:57.072+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:43:57.063+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:43:57.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:43:57.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.131 seconds
[2024-11-19T16:44:27.550+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:27.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:44:27.557+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:44:27.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:27.600+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:44:27.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:44:27.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:27.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.121 seconds
[2024-11-19T16:44:58.100+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:58.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:44:58.108+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:44:58.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:58.153+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:44:58.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:44:58.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:44:58.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.140 seconds
[2024-11-19T16:45:28.674+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:28.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:45:28.681+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:45:28.681+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:28.733+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:45:28.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:45:28.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:28.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.141 seconds
[2024-11-19T16:45:59.230+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:59.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:45:59.238+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:45:59.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:59.276+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:45:59.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:45:59.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:45:59.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.131 seconds
[2024-11-19T16:46:29.791+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:46:29.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:46:29.798+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:46:29.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:46:29.835+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:46:29.826+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:46:29.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:46:29.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.125 seconds
[2024-11-19T16:47:00.362+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:00.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:47:00.371+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:47:00.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:00.409+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:47:00.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:47:00.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:00.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.125 seconds
[2024-11-19T16:47:30.939+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:30.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:47:30.948+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:47:30.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:30.987+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:47:30.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:47:30.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:47:31.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.126 seconds
[2024-11-19T16:48:01.616+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:01.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:48:01.623+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:48:01.622+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:01.663+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:48:01.654+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:48:01.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:01.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.118 seconds
[2024-11-19T16:48:32.150+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:32.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:48:32.157+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:48:32.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:32.199+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:48:32.188+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:48:32.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:48:32.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.114 seconds
[2024-11-19T16:49:02.686+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:02.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:49:02.701+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:49:02.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:02.742+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:49:02.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:49:02.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:02.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.144 seconds
[2024-11-19T16:49:33.217+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:33.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:49:33.224+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:49:33.223+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:33.263+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:49:33.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:49:33.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:49:33.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.116 seconds
[2024-11-19T16:50:03.746+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:03.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:50:03.752+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:50:03.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:03.792+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:50:03.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:50:03.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:03.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.115 seconds
[2024-11-19T16:50:34.276+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:34.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:50:34.283+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:50:34.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:34.321+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:50:34.312+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:50:34.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:50:34.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.111 seconds
[2024-11-19T16:51:04.788+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:04.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:51:04.795+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:51:04.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:04.831+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:51:04.823+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:51:04.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:04.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.114 seconds
[2024-11-19T16:51:35.259+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:35.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:51:35.265+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:51:35.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:35.303+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:51:35.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:51:35.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:51:35.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.112 seconds
[2024-11-19T16:52:05.706+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:05.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:52:05.714+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:52:05.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:05.753+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:52:05.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:52:05.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:05.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.115 seconds
[2024-11-19T16:52:36.301+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:36.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:52:36.311+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:52:36.311+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:36.356+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:52:36.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:52:36.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:52:36.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.136 seconds
[2024-11-19T16:53:06.994+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:06.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:53:07.002+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:53:07.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:07.049+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:53:07.038+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:53:07.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:07.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.125 seconds
[2024-11-19T16:53:37.508+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:37.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:53:37.515+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:53:37.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:37.559+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:53:37.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:53:37.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:53:37.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.118 seconds
[2024-11-19T16:54:08.125+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:08.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:54:08.132+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:54:08.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:08.173+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:54:08.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:54:08.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:08.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T16:54:38.629+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:38.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:54:38.636+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:54:38.635+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:38.684+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:54:38.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:54:38.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:54:38.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T16:55:09.213+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:09.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:55:09.220+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:55:09.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:09.261+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:55:09.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:55:09.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:09.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.113 seconds
[2024-11-19T16:55:39.753+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:39.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:55:39.762+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:55:39.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:39.805+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:55:39.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:55:39.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:55:39.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.129 seconds
[2024-11-19T16:56:10.280+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:10.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:56:10.287+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:56:10.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:10.331+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:56:10.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:56:10.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:10.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T16:56:40.773+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:40.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:56:40.780+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:56:40.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:40.822+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:56:40.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:56:40.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:56:40.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.117 seconds
[2024-11-19T16:57:11.361+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:11.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:57:11.367+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:57:11.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:11.404+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:57:11.396+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:57:11.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:11.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.104 seconds
[2024-11-19T16:57:41.868+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:41.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:57:41.875+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:57:41.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:41.921+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:57:41.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:57:41.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:57:41.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.123 seconds
[2024-11-19T16:58:12.520+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:12.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:58:12.527+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:58:12.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:12.574+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:58:12.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:58:12.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:12.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.122 seconds
[2024-11-19T16:58:43.033+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:43.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:58:43.040+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:58:43.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:43.085+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:58:43.075+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:58:43.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:58:43.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T16:59:13.563+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:13.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:59:13.570+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:59:13.570+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:13.612+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:59:13.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:59:13.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:13.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.116 seconds
[2024-11-19T16:59:44.163+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:44.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T16:59:44.170+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:59:44.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:44.209+0000] {logging_mixin.py:188} INFO - [2024-11-19T16:59:44.200+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T16:59:44.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T16:59:44.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.108 seconds
[2024-11-19T17:00:14.693+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:14.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:00:14.701+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:00:14.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:14.744+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:00:14.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:00:14.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:14.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.111 seconds
[2024-11-19T17:00:45.175+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:45.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:00:45.181+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:00:45.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:45.221+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:00:45.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:00:45.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:00:45.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.117 seconds
[2024-11-19T17:01:15.674+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:15.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:01:15.680+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:01:15.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:15.725+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:01:15.715+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:01:15.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:15.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.133 seconds
[2024-11-19T17:01:46.235+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:46.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:01:46.243+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:01:46.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:46.290+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:01:46.279+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:01:46.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:01:46.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.126 seconds
[2024-11-19T17:02:16.751+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:16.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:02:16.759+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:02:16.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:16.800+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:02:16.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:02:16.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:16.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.111 seconds
[2024-11-19T17:02:47.233+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:47.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:02:47.239+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:02:47.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:47.288+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:02:47.276+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:02:47.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:02:47.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.132 seconds
[2024-11-19T17:03:17.900+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:17.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:03:17.907+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:03:17.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:17.946+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:03:17.937+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:03:17.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:17.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.108 seconds
[2024-11-19T17:03:48.381+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:48.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:03:48.388+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:03:48.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:48.428+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:03:48.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:03:48.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:03:48.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.105 seconds
[2024-11-19T17:04:19.004+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:19.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:04:19.012+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:04:19.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:19.053+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:04:19.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:04:19.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:19.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.124 seconds
[2024-11-19T17:04:49.528+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:49.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:04:49.535+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:04:49.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:49.584+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:04:49.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:04:49.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:04:49.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T17:05:20.026+0000] {processor.py:161} INFO - Started process (PID=463) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:20.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:05:20.032+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:05:20.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:20.072+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:05:20.063+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:05:20.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:20.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.122 seconds
[2024-11-19T17:05:50.602+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:50.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:05:50.609+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:05:50.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:50.652+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:05:50.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:05:50.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:05:50.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.116 seconds
[2024-11-19T17:06:21.125+0000] {processor.py:161} INFO - Started process (PID=479) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:21.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:06:21.133+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:06:21.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:21.177+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:06:21.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:06:21.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:21.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.128 seconds
[2024-11-19T17:06:51.633+0000] {processor.py:161} INFO - Started process (PID=487) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:51.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:06:51.639+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:06:51.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:51.678+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:06:51.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:06:51.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:06:51.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.111 seconds
[2024-11-19T17:07:22.134+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:22.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:07:22.141+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:07:22.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:22.183+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:07:22.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:07:22.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:22.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T17:07:52.655+0000] {processor.py:161} INFO - Started process (PID=503) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:52.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:07:52.664+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:07:52.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:52.706+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:07:52.695+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:07:52.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:07:52.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.126 seconds
[2024-11-19T17:08:23.389+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:23.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:08:23.397+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:08:23.396+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:23.435+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:08:23.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:08:23.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:23.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.121 seconds
[2024-11-19T17:08:53.898+0000] {processor.py:161} INFO - Started process (PID=519) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:53.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:08:53.904+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:08:53.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:53.944+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:08:53.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:08:53.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:08:53.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.110 seconds
[2024-11-19T17:09:24.365+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:24.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:09:24.373+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:09:24.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:24.417+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:09:24.407+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:09:24.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:24.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.121 seconds
[2024-11-19T17:09:54.867+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:54.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:09:54.874+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:09:54.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:54.918+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:09:54.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:09:54.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:09:54.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.123 seconds
[2024-11-19T17:10:25.430+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:25.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:10:25.438+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:10:25.437+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:25.479+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:10:25.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:10:25.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:25.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.120 seconds
[2024-11-19T17:10:56.007+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:56.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:10:56.014+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:10:56.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:56.057+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:10:56.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:10:56.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:10:56.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.116 seconds
[2024-11-19T17:11:26.488+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:26.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:11:26.495+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:11:26.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:26.537+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:11:26.527+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:11:26.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:26.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.120 seconds
[2024-11-19T17:11:56.974+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:56.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:11:56.981+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:11:56.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:57.026+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:11:57.017+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:11:57.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:11:57.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.126 seconds
[2024-11-19T17:12:27.493+0000] {processor.py:161} INFO - Started process (PID=575) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:27.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:12:27.499+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:12:27.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:27.540+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:12:27.530+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:12:27.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:27.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.118 seconds
[2024-11-19T17:12:58.127+0000] {processor.py:161} INFO - Started process (PID=583) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:58.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:12:58.135+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:12:58.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:58.179+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:12:58.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:12:58.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:12:58.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.118 seconds
[2024-11-19T17:13:28.609+0000] {processor.py:161} INFO - Started process (PID=591) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:28.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:13:28.616+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:13:28.615+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:28.659+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:13:28.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:13:28.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:28.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.123 seconds
[2024-11-19T17:13:59.067+0000] {processor.py:161} INFO - Started process (PID=599) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:59.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:13:59.075+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:13:59.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:59.117+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:13:59.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:13:59.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:13:59.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.115 seconds
[2024-11-19T17:14:29.523+0000] {processor.py:161} INFO - Started process (PID=607) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:14:29.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:14:29.530+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:14:29.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:14:29.574+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:14:29.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:14:29.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:14:29.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T17:15:00.084+0000] {processor.py:161} INFO - Started process (PID=615) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:00.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:15:00.091+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:15:00.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:00.132+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:15:00.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:15:00.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:00.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.117 seconds
[2024-11-19T17:15:30.612+0000] {processor.py:161} INFO - Started process (PID=623) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:30.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:15:30.622+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:15:30.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:30.664+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:15:30.655+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:15:30.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:15:30.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.138 seconds
[2024-11-19T17:16:01.100+0000] {processor.py:161} INFO - Started process (PID=631) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:01.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:16:01.107+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:16:01.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:01.146+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:16:01.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:16:01.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:01.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.115 seconds
[2024-11-19T17:16:31.686+0000] {processor.py:161} INFO - Started process (PID=639) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:31.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:16:31.695+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:16:31.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:31.736+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:16:31.727+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:16:31.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:16:31.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.121 seconds
[2024-11-19T17:17:02.161+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:02.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:17:02.168+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:17:02.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:02.215+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:17:02.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:17:02.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:02.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.121 seconds
[2024-11-19T17:17:32.661+0000] {processor.py:161} INFO - Started process (PID=655) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:32.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:17:32.668+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:17:32.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:32.712+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:17:32.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:17:32.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:17:32.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.119 seconds
[2024-11-19T17:58:20.841+0000] {processor.py:161} INFO - Started process (PID=657) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:20.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:58:20.847+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:58:20.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:20.883+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:58:20.874+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:58:20.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:20.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.117 seconds
[2024-11-19T17:58:51.456+0000] {processor.py:161} INFO - Started process (PID=665) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:51.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:58:51.464+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:58:51.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:51.509+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:58:51.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:58:51.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:58:51.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.126 seconds
[2024-11-19T17:59:21.789+0000] {processor.py:161} INFO - Started process (PID=674) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:21.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:59:21.792+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:59:21.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:21.804+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:59:21.801+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:59:21.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:21.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.039 seconds
[2024-11-19T17:59:52.004+0000] {processor.py:161} INFO - Started process (PID=682) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:52.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T17:59:52.006+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:59:52.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:52.017+0000] {logging_mixin.py:188} INFO - [2024-11-19T17:59:52.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T17:59:52.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T17:59:52.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:00:22.188+0000] {processor.py:161} INFO - Started process (PID=690) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:22.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:00:22.191+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:00:22.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:22.201+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:00:22.199+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:00:22.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:22.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:00:52.391+0000] {processor.py:161} INFO - Started process (PID=698) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:52.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:00:52.393+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:00:52.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:52.403+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:00:52.400+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:00:52.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:00:52.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.034 seconds
[2024-11-19T18:01:22.637+0000] {processor.py:161} INFO - Started process (PID=707) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:22.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:01:22.640+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:01:22.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:22.652+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:01:22.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:01:22.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:22.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.039 seconds
[2024-11-19T18:01:52.890+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:52.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:01:52.892+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:01:52.892+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:52.903+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:01:52.901+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:01:52.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:01:52.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:02:23.144+0000] {processor.py:161} INFO - Started process (PID=723) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:23.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:02:23.146+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:02:23.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:23.158+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:02:23.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:02:23.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:23.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.043 seconds
[2024-11-19T18:02:53.353+0000] {processor.py:161} INFO - Started process (PID=731) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:53.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:02:53.356+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:02:53.355+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:53.365+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:02:53.363+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:02:53.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:02:53.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:03:23.611+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:23.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:03:23.613+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:03:23.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:23.624+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:03:23.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:03:23.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:23.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:03:53.828+0000] {processor.py:161} INFO - Started process (PID=753) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:53.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:03:53.831+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:03:53.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:53.841+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:03:53.838+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:03:53.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:03:53.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:04:24.045+0000] {processor.py:161} INFO - Started process (PID=761) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:24.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:04:24.048+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:04:24.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:24.057+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:04:24.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:04:24.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:24.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:04:54.315+0000] {processor.py:161} INFO - Started process (PID=769) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:54.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:04:54.323+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:04:54.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:54.348+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:04:54.343+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:04:54.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:04:54.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.105 seconds
[2024-11-19T18:05:24.573+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:24.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:05:24.575+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:05:24.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:24.587+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:05:24.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:05:24.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:24.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:05:54.788+0000] {processor.py:161} INFO - Started process (PID=785) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:54.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:05:54.790+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:05:54.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:54.802+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:05:54.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:05:54.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:05:54.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.037 seconds
[2024-11-19T18:06:25.026+0000] {processor.py:161} INFO - Started process (PID=793) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:25.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:06:25.029+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:06:25.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:25.041+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:06:25.038+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:06:25.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:25.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:06:55.256+0000] {processor.py:161} INFO - Started process (PID=801) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:55.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:06:55.259+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:06:55.259+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:55.271+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:06:55.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:06:55.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:06:55.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:07:25.495+0000] {processor.py:161} INFO - Started process (PID=809) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:25.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:07:25.497+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:07:25.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:25.508+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:07:25.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:07:25.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:25.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.039 seconds
[2024-11-19T18:07:55.730+0000] {processor.py:161} INFO - Started process (PID=817) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:55.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:07:55.732+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:07:55.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:55.742+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:07:55.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:07:55.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:07:55.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:08:25.990+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:25.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:08:25.992+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:08:25.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:26.003+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:08:26.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:08:26.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:26.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:08:56.198+0000] {processor.py:161} INFO - Started process (PID=833) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:56.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:08:56.200+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:08:56.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:56.210+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:08:56.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:08:56.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:08:56.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:09:26.427+0000] {processor.py:161} INFO - Started process (PID=841) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:26.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:09:26.430+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:09:26.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:26.441+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:09:26.439+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:09:26.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:26.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.045 seconds
[2024-11-19T18:09:56.651+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:56.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:09:56.653+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:09:56.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:56.665+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:09:56.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:09:56.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:09:56.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.043 seconds
[2024-11-19T18:10:26.849+0000] {processor.py:161} INFO - Started process (PID=857) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:26.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:10:26.851+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:10:26.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:26.861+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:10:26.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:10:26.862+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:26.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:10:57.082+0000] {processor.py:161} INFO - Started process (PID=865) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:57.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:10:57.085+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:10:57.084+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:57.096+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:10:57.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:10:57.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:10:57.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.048 seconds
[2024-11-19T18:11:27.331+0000] {processor.py:161} INFO - Started process (PID=873) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:27.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:11:27.334+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:11:27.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:27.345+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:11:27.342+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:11:27.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:27.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:11:57.525+0000] {processor.py:161} INFO - Started process (PID=881) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:57.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:11:57.528+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:11:57.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:57.538+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:11:57.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:11:57.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:11:57.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.043 seconds
[2024-11-19T18:12:27.711+0000] {processor.py:161} INFO - Started process (PID=889) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:27.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:12:27.714+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:12:27.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:27.724+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:12:27.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:12:27.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:27.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:12:57.944+0000] {processor.py:161} INFO - Started process (PID=897) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:57.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:12:57.947+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:12:57.946+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:57.956+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:12:57.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:12:57.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:12:57.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:13:28.173+0000] {processor.py:161} INFO - Started process (PID=905) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:28.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:13:28.175+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:13:28.175+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:28.187+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:13:28.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:13:28.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:28.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.039 seconds
[2024-11-19T18:13:58.361+0000] {processor.py:161} INFO - Started process (PID=913) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:58.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:13:58.364+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:13:58.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:58.382+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:13:58.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:13:58.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:13:58.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.050 seconds
[2024-11-19T18:14:28.571+0000] {processor.py:161} INFO - Started process (PID=921) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:28.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:14:28.573+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:14:28.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:28.584+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:14:28.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:14:28.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:28.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:14:58.796+0000] {processor.py:161} INFO - Started process (PID=929) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:58.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:14:58.799+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:14:58.799+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:58.809+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:14:58.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:14:58.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:14:58.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:15:28.996+0000] {processor.py:161} INFO - Started process (PID=937) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:28.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:15:28.999+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:15:28.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:29.009+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:15:29.006+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:15:29.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:29.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:15:59.234+0000] {processor.py:161} INFO - Started process (PID=945) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:59.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:15:59.237+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:15:59.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:59.248+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:15:59.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:15:59.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:15:59.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.043 seconds
[2024-11-19T18:16:29.430+0000] {processor.py:161} INFO - Started process (PID=953) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:29.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:16:29.432+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:16:29.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:29.445+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:16:29.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:16:29.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:29.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.046 seconds
[2024-11-19T18:16:59.594+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:59.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:16:59.596+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:16:59.596+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:59.608+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:16:59.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:16:59.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:16:59.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:17:29.790+0000] {processor.py:161} INFO - Started process (PID=969) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:17:29.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:17:29.792+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:17:29.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:17:29.802+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:17:29.800+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:17:29.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:17:29.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:17:59.970+0000] {processor.py:161} INFO - Started process (PID=977) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:17:59.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:17:59.973+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:17:59.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:17:59.984+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:17:59.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:17:59.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:18:00.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:18:30.209+0000] {processor.py:161} INFO - Started process (PID=985) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:18:30.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:18:30.212+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:18:30.212+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:18:30.222+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:18:30.219+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:18:30.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:18:30.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:19:00.381+0000] {processor.py:161} INFO - Started process (PID=993) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:00.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:19:00.383+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:19:00.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:00.393+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:19:00.391+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:19:00.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:00.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:19:30.589+0000] {processor.py:161} INFO - Started process (PID=1001) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:30.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:19:30.591+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:19:30.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:30.602+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:19:30.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:19:30.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:19:30.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:20:00.757+0000] {processor.py:161} INFO - Started process (PID=1009) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:00.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:20:00.759+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:20:00.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:00.769+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:20:00.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:20:00.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:00.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.037 seconds
[2024-11-19T18:20:30.946+0000] {processor.py:161} INFO - Started process (PID=1017) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:30.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:20:30.948+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:20:30.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:30.960+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:20:30.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:20:30.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:20:30.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:21:01.113+0000] {processor.py:161} INFO - Started process (PID=1025) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:01.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:21:01.115+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:21:01.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:01.125+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:21:01.123+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:21:01.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:01.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:21:31.326+0000] {processor.py:161} INFO - Started process (PID=1033) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:31.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:21:31.328+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:21:31.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:31.339+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:21:31.336+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:21:31.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:21:31.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:22:01.510+0000] {processor.py:161} INFO - Started process (PID=1041) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:01.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:22:01.512+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:22:01.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:01.522+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:22:01.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:22:01.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:01.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:22:31.735+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:31.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:22:31.738+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:22:31.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:31.748+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:22:31.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:22:31.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:22:31.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:23:01.942+0000] {processor.py:161} INFO - Started process (PID=1057) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:01.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:23:01.945+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:23:01.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:01.955+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:23:01.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:23:01.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:01.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.045 seconds
[2024-11-19T18:23:32.160+0000] {processor.py:161} INFO - Started process (PID=1065) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:32.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:23:32.163+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:23:32.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:32.173+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:23:32.171+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:23:32.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:23:32.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:24:02.382+0000] {processor.py:161} INFO - Started process (PID=1073) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:02.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:24:02.384+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:24:02.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:02.394+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:24:02.392+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:24:02.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:02.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:24:32.565+0000] {processor.py:161} INFO - Started process (PID=1081) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:32.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:24:32.568+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:24:32.567+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:32.579+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:24:32.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:24:32.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:24:32.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:25:02.758+0000] {processor.py:161} INFO - Started process (PID=1089) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:02.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:25:02.760+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:25:02.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:02.771+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:25:02.768+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:25:02.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:02.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:25:32.960+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:32.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:25:32.963+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:25:32.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:32.974+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:25:32.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:25:32.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:25:32.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.039 seconds
[2024-11-19T18:26:03.196+0000] {processor.py:161} INFO - Started process (PID=1105) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:03.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:26:03.199+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:26:03.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:03.209+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:26:03.207+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:26:03.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:03.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.041 seconds
[2024-11-19T18:26:33.354+0000] {processor.py:161} INFO - Started process (PID=1113) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:33.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:26:33.357+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:26:33.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:33.367+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:26:33.365+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:26:33.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:26:33.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:27:03.548+0000] {processor.py:161} INFO - Started process (PID=1121) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:03.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:27:03.551+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:27:03.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:03.560+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:27:03.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:27:03.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:03.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.034 seconds
[2024-11-19T18:27:33.755+0000] {processor.py:161} INFO - Started process (PID=1129) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:33.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:27:33.758+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:27:33.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:33.768+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:27:33.766+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:27:33.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:27:33.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.035 seconds
[2024-11-19T18:28:03.943+0000] {processor.py:161} INFO - Started process (PID=1138) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:03.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:28:03.945+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:28:03.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:03.956+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:28:03.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:28:03.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:03.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:28:34.166+0000] {processor.py:161} INFO - Started process (PID=1146) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:34.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:28:34.168+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:28:34.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:34.178+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:28:34.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:28:34.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:28:34.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
[2024-11-19T18:29:04.359+0000] {processor.py:161} INFO - Started process (PID=1154) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:04.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:29:04.362+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:29:04.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:04.372+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:29:04.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:29:04.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:04.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.042 seconds
[2024-11-19T18:29:34.536+0000] {processor.py:161} INFO - Started process (PID=1162) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:34.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:29:34.539+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:29:34.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:34.550+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:29:34.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:29:34.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:29:34.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:30:04.702+0000] {processor.py:161} INFO - Started process (PID=1170) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:04.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:30:04.704+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:30:04.704+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:04.714+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:30:04.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:30:04.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:04.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:30:34.895+0000] {processor.py:161} INFO - Started process (PID=1178) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:34.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:30:34.897+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:30:34.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:34.906+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:30:34.904+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:30:34.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:30:34.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.040 seconds
[2024-11-19T18:31:04.965+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:31:04.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:31:04.967+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:31:04.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:31:04.976+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:31:04.974+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:31:04.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:31:04.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.038 seconds
[2024-11-19T18:55:53.142+0000] {processor.py:161} INFO - Started process (PID=1194) to work on /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:55:53.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/data_ingestion.py for tasks to queue
[2024-11-19T18:55:53.144+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:55:53.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:55:53.155+0000] {logging_mixin.py:188} INFO - [2024-11-19T18:55:53.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.py", line 15, in <module>
    from include.dbt.cosmos_config import DBT_PROJECT_CONFIG, DBT_CONFIG
ModuleNotFoundError: No module named 'include'
[2024-11-19T18:55:53.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.py
[2024-11-19T18:55:53.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/data_ingestion.py took 0.036 seconds
