[2024-11-12T08:11:44.153+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T08:11:44.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_green_tripdata_raw scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T08:11:44.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.upload_green_tripdata_raw scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T08:11:44.209+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T08:11:44.242+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_green_tripdata_raw> on 2024-11-11 00:00:00+00:00
[2024-11-12T08:11:44.255+0000] {standard_task_runner.py:64} INFO - Started process 106 to run task
[2024-11-12T08:11:44.259+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'upload_green_tripdata_raw', 'scheduled__2024-11-11T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpq679rqjg']
[2024-11-12T08:11:44.263+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask upload_green_tripdata_raw
[2024-11-12T08:11:44.353+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.upload_green_tripdata_raw scheduled__2024-11-11T00:00:00+00:00 [running]> on host a8b5a6a20900
[2024-11-12T08:11:44.528+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='upload_green_tripdata_raw' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T00:00:00+00:00'
[2024-11-12T08:11:44.530+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T08:11:44.555+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-11-12T08:11:44.557+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-12T08:11:44.559+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-12T08:11:44.561+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T08:11:44.562+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 114, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 362, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 334, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 257, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 315, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/oauth2/service_account.py", line 259, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/include/.gcp/service_account.json'
[2024-11-12T08:11:44.580+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=upload_green_tripdata_raw, run_id=scheduled__2024-11-11T00:00:00+00:00, execution_date=20241111T000000, start_date=20241112T081144, end_date=20241112T081144
[2024-11-12T08:11:44.603+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task upload_green_tripdata_raw ([Errno 2] No such file or directory: '/include/.gcp/service_account.json'; 106)
[2024-11-12T08:11:44.642+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-12T08:11:44.691+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T08:11:44.696+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
